"""
nexoria.desktop.electron
===========================
Scaffolds a real Electron project that wraps a Nexoria app as a
desktop application: Electron's main process spawns your Python
server as a child process, waits for it to come up (polling
`/_nexoria/health`, which every `App` already serves), opens a
`BrowserWindow` pointing at it, and kills the child process on quit.

This is genuinely different from Nexoria's client-side library
integrations above -- there's no "adapter" running inside your app;
this generates a small, separate Electron project (main.js, preload.js,
package.json) alongside your Nexoria app, invoked via `nexoria
build-desktop`. Building the actual installer needs Node + Electron +
electron-builder on the machine doing the packaging (same "build-time
only" tooling story as `nexoria build`'s esbuild step) -- never on end
users' machines, who just run the packaged app.
"""

from __future__ import annotations
import json
import os

MAIN_JS_TEMPLATE = '''\
// Electron main process for {app_name}, generated by
// `nexoria build-desktop`. Spawns the Python server as a child
// process, waits for it to report healthy, then opens a window
// pointing at it.
const {{ app, BrowserWindow }} = require("electron");
const {{ spawn }} = require("child_process");
const path = require("path");
const http = require("http");

const PORT = {port};
const PYTHON_CMD = process.env.NEXORIA_PYTHON || "python3";
const APP_ENTRY = path.join(__dirname, "..", "{entry_file}");

let serverProcess = null;
let mainWindow = null;

function waitForServer(url, timeoutMs, onReady) {{
  const start = Date.now();
  (function poll() {{
    http.get(url, (res) => {{
      if (res.statusCode === 200) return onReady();
      retry();
    }}).on("error", retry);
    function retry() {{
      if (Date.now() - start > timeoutMs) {{
        console.error("Nexoria desktop: server did not become healthy in time");
        app.quit();
        return;
      }}
      setTimeout(poll, 200);
    }}
  }})();
}}

function startServer() {{
  serverProcess = spawn(PYTHON_CMD, [APP_ENTRY], {{
    stdio: "inherit",
    env: Object.assign({{}}, process.env, {{ NEXORIA_DESKTOP: "1" }}),
  }});
  serverProcess.on("error", (err) => {{
    console.error("Nexoria desktop: failed to start Python server:", err);
  }});
}}

function createWindow() {{
  mainWindow = new BrowserWindow({{
    width: 1200,
    height: 800,
    title: "{app_name}",
    webPreferences: {{
      preload: path.join(__dirname, "preload.js"),
      contextIsolation: true,
      nodeIntegration: false,
    }},
  }});
  mainWindow.loadURL(`http://127.0.0.1:${{PORT}}/`);
}}

app.whenReady().then(() => {{
  startServer();
  waitForServer(`http://127.0.0.1:${{PORT}}/_nexoria/health`, 15000, createWindow);

  app.on("activate", () => {{
    if (BrowserWindow.getAllWindows().length === 0) createWindow();
  }});
}});

app.on("window-all-closed", () => {{
  if (process.platform !== "darwin") app.quit();
}});

app.on("before-quit", () => {{
  if (serverProcess) serverProcess.kill();
}});
'''

PRELOAD_JS_TEMPLATE = '''\
// Minimal preload script for {app_name} -- contextIsolation is on and
// nodeIntegration is off in main.js (Electron's recommended secure
// default), so nothing is exposed to the renderer by default. Add
// `contextBridge.exposeInMainWorld(...)` calls here if your app needs
// to call back into Node/Electron APIs from the Nexoria-rendered page.
const {{ contextBridge }} = require("electron");

contextBridge.exposeInMainWorld("nexoriaDesktop", {{
  platform: process.platform,
}});
'''


def scaffold_electron(
    project_dir: str,
    app_name: str = "Nexoria App",
    entry_file: str = "app.py",
    port: int = 8000,
    app_id: str = "com.pythonaibrain.nexoria-app",
) -> str:
    """
    Write a complete Electron project into `<project_dir>/electron/`.
    Returns the path to that directory. Idempotent: safe to re-run
    after editing your app -- overwrites the generated files, never
    touches your own `app.py`.
    """
    electron_dir = os.path.join(project_dir, "electron")
    os.makedirs(electron_dir, exist_ok=True)

    with open(os.path.join(electron_dir, "main.js"), "w") as f:
        f.write(MAIN_JS_TEMPLATE.format(app_name=app_name, port=port, entry_file=entry_file))

    with open(os.path.join(electron_dir, "preload.js"), "w") as f:
        f.write(PRELOAD_JS_TEMPLATE.format(app_name=app_name))

    package_json = {
        "name": app_id.split(".")[-1],
        "version": "0.1.0",
        "private": True,
        "description": f"Desktop build of {app_name}, generated by `nexoria build-desktop`.",
        "main": "main.js",
        "scripts": {
            "start": "electron .",
            "dist": "electron-builder",
        },
        "devDependencies": {
            "electron": "^33.0.0",
            "electron-builder": "^25.0.0",
        },
        "build": {
            "appId": app_id,
            "productName": app_name,
            "files": ["**/*"],
            "extraResources": [{"from": f"../{entry_file}", "to": entry_file}],
            "mac": {"category": "public.app-category.utilities"},
            "win": {"target": "nsis"},
            "linux": {"target": "AppImage"},
        },
    }
    with open(os.path.join(electron_dir, "package.json"), "w") as f:
        json.dump(package_json, f, indent=2)

    return electron_dir
