"""
nexoria.mobile.capacitor
============================
Scaffolds a Capacitor project that wraps a Nexoria app as a native
iOS/Android shell.

Honest architectural constraint, read before using this: Capacitor
wraps a **webview** -- it doesn't run a Python process on-device.
Nexoria's server-rendered, WebSocket-patched architecture (real
Python state, live diff/patch updates) needs an actual running Python
server somewhere. There is no realistic way to embed the Python
runtime + your app's dependencies inside a Capacitor app the way you
could bundle static HTML/JS. This generator therefore configures
Capacitor's webview to point at your **deployed** Nexoria server's URL
(`server.url` in `capacitor.config.json`) -- an officially supported,
documented Capacitor pattern for exactly this "native shell around a
remote web app" case, not a workaround. Your Python backend needs to be
deployed and reachable (over HTTPS in production) before the mobile
app is useful; this generator does not deploy it for you.

If what you actually want is a fully offline-capable native app with
no server dependency, Capacitor isn't the right fit for a
Nexoria app's architecture -- that would need a client-only rewrite
of your UI logic, which is a different (and much larger) undertaking
than this scaffolding step.
"""

from __future__ import annotations
import json
import os


def scaffold_capacitor(
    project_dir: str,
    app_name: str = "Nexoria App",
    app_id: str = "com.pythonaibrain.nexoriaapp",
    server_url: str = "https://your-deployed-app.example.com",
) -> str:
    """
    Write a Capacitor project config into `<project_dir>/mobile/`.
    Returns the path to that directory.

    `server_url` MUST be your actual deployed backend's URL before
    this is useful on a real device -- the placeholder default will
    load nothing. Update it, or pass the real one in directly.
    """
    mobile_dir = os.path.join(project_dir, "mobile")
    os.makedirs(mobile_dir, exist_ok=True)

    capacitor_config = {
        "appId": app_id,
        "appName": app_name,
        "webDir": "www",  # required by Capacitor's schema even though we're in remote mode; left as an empty placeholder dir
        "server": {
            "url": server_url,
            "cleartext": server_url.startswith("http://"),
        },
    }
    with open(os.path.join(mobile_dir, "capacitor.config.json"), "w") as f:
        json.dump(capacitor_config, f, indent=2)

    # Capacitor's CLI expects webDir to exist even in remote mode.
    www_dir = os.path.join(mobile_dir, "www")
    os.makedirs(www_dir, exist_ok=True)
    with open(os.path.join(www_dir, "index.html"), "w") as f:
        f.write(
            "<!-- Placeholder: this app loads content from "
            f"{server_url} at runtime (see capacitor.config.json's "
            "server.url) -- this file is never actually shown. -->\n"
            "<!DOCTYPE html><html><body></body></html>\n"
        )

    package_json = {
        "name": app_id.split(".")[-1],
        "version": "0.1.0",
        "private": True,
        "description": f"Mobile shell for {app_name} (webview pointed at a deployed Nexoria backend), generated by `nexoria build-mobile`.",
        "dependencies": {
            "@capacitor/core": "^7.0.0",
        },
        "devDependencies": {
            "@capacitor/cli": "^7.0.0",
            "@capacitor/android": "^7.0.0",
            "@capacitor/ios": "^7.0.0",
        },
        "scripts": {
            "add:android": "cap add android",
            "add:ios": "cap add ios",
            "sync": "cap sync",
            "open:android": "cap open android",
            "open:ios": "cap open ios",
        },
    }
    with open(os.path.join(mobile_dir, "package.json"), "w") as f:
        json.dump(package_json, f, indent=2)

    return mobile_dir
